name: Deploy Quizify-Frontend

on: 
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t harshitalavania/quiz-portal-frontend .


      - name: Publish Image to docker hub
        run: docker push harshitalavania/quiz-portal-frontend:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull harshitalavania/quiz-portal-frontend:latest
      - name: Delete old container
        run: docker rm -f quizify-frontend-container 
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name quizify-frontend-container harshitalavania/quiz-portal-frontend